name: unidata-standard
channels:
  - conda-forge
dependencies:
  # Required by JupyterLab
  - 'python<3.13'
  - nb_conda_kernels
  - ipykernel
  # User requested packages
  - metpy
  - sharppy
  - numpy
  - pandas
  - seaborn
  - matplotlib
  - pip:
    # It is recommended to install a package using pip as a last resort, i.e.
    # when it is not found in the conda repos
    - palmerpenguins # Example data set for data exploration and visualization
